In [68]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

In [69]:
trn_N = np.load(r"Train_MFCC_N_2000.npy")

In [70]:
trn_N

array([[-3.07566538, -7.51789641, -1.37935714, ..., -0.18227882,
        -0.12802416, -0.05514341],
       [-4.74620322, -8.24191711, -3.29561593, ..., -0.18227882,
        -0.12802416, -0.05514341],
       [-6.14211871, -7.14666554, -3.27335573, ..., -0.18227882,
        -0.12802416, -0.05514341],
       ...,
       [-4.39090674, -3.09281549, -3.0825913 , ...,  0.02837132,
        -0.04985337, -0.08317881],
       [-2.95050379, -1.82564897, -2.37364633, ..., -0.08259737,
        -0.07048922, -0.11595972],
       [-3.19085279, -2.55945859, -2.20408458, ..., -0.13178694,
        -0.03207238, -0.12605519]])

In [71]:
trn_N.shape

(2000, 60)

In [72]:
trn_S = np.load(r"Train_MFCC_S_2000.npy")

In [73]:
trn_S

array([[-1.93120017e+00, -8.69720499e+00, -3.49635365e+00, ...,
        -3.77318920e-02,  1.37528645e-02,  8.43636746e-02],
       [-2.37015629e+00, -8.50103375e+00, -3.38788939e+00, ...,
        -3.77318920e-02,  1.37528645e-02,  8.43636746e-02],
       [-1.21453927e+00, -7.43380569e+00, -2.07692403e+00, ...,
        -3.77318920e-02,  1.37528645e-02,  8.43636746e-02],
       ...,
       [ 7.56875746e-01,  4.15979972e-01, -4.21288898e-01, ...,
         8.60875819e-02, -6.18213231e-02,  6.97702518e-03],
       [ 6.43663569e-01, -4.46740069e-01, -3.08523381e-01, ...,
         1.47687822e-01, -5.41443317e-02,  2.54369165e-02],
       [ 1.08964890e+00,  3.01069650e-01, -3.02065055e-01, ...,
         1.09762055e-01, -2.15156070e-02,  4.13514484e-02]])

In [74]:
trn_S.shape

(2000, 60)

In [75]:
trn_D = np.append(trn_N, trn_S, axis = 0)

In [76]:
trn_D

array([[-3.07566538e+00, -7.51789641e+00, -1.37935714e+00, ...,
        -1.82278820e-01, -1.28024164e-01, -5.51434103e-02],
       [-4.74620322e+00, -8.24191711e+00, -3.29561593e+00, ...,
        -1.82278820e-01, -1.28024164e-01, -5.51434103e-02],
       [-6.14211871e+00, -7.14666554e+00, -3.27335573e+00, ...,
        -1.82278820e-01, -1.28024164e-01, -5.51434103e-02],
       ...,
       [ 7.56875746e-01,  4.15979972e-01, -4.21288898e-01, ...,
         8.60875819e-02, -6.18213231e-02,  6.97702518e-03],
       [ 6.43663569e-01, -4.46740069e-01, -3.08523381e-01, ...,
         1.47687822e-01, -5.41443317e-02,  2.54369165e-02],
       [ 1.08964890e+00,  3.01069650e-01, -3.02065055e-01, ...,
         1.09762055e-01, -2.15156070e-02,  4.13514484e-02]])

In [77]:
trn_D.shape

(4000, 60)

In [78]:
meanVec = np.mean(trn_D, axis =0)

In [79]:
meanVec

array([-3.31329677e+00, -5.64740375e+00, -9.04938985e-01, -2.86477791e+00,
       -3.61611627e-01, -6.89577941e-01, -2.08948888e+00, -3.30836706e-01,
       -9.37393949e-01,  2.01619058e-01, -1.52629510e+00, -1.90115878e-01,
        2.14919129e-01, -4.65294013e-01,  3.71386108e-01,  2.94936120e-01,
       -3.13286401e-01,  1.66839499e-01, -1.84446526e-01,  1.38552236e-01,
        5.40011131e-03,  4.65855450e-02,  3.78674646e-03,  3.14272654e-02,
        1.94516715e-03, -1.83958240e-03, -4.27767454e-03, -2.09801403e-02,
       -4.24944706e-03, -2.88295245e-02,  2.69013814e-03, -1.34489114e-02,
       -1.14635389e-02, -2.02283508e-03, -1.06158874e-02, -5.43531662e-03,
       -3.89738340e-03, -1.76978972e-03, -3.42742954e-03,  9.15447716e-04,
       -9.90105966e-03,  4.21258512e-03,  7.97629168e-03,  5.83546775e-03,
       -2.11301472e-04, -1.33823428e-03, -6.62625540e-04, -2.16314075e-03,
        1.50532100e-06, -4.15767673e-03,  4.53568416e-04, -1.30994395e-03,
       -1.21025468e-03,  

In [80]:
stdVec = np.std(trn_D, axis =0)

In [81]:
stdVec

array([3.25894632, 2.77050226, 2.0314233 , 1.32066965, 1.44729642,
       1.40622818, 0.92587198, 1.18173321, 0.81388116, 1.01638139,
       0.78761382, 1.12825927, 0.90320687, 1.09002095, 1.03344846,
       0.9261113 , 1.04067999, 1.14673699, 1.13511034, 1.01631303,
       0.51450298, 0.57162649, 0.39585492, 0.35886599, 0.29308901,
       0.29864307, 0.23410426, 0.30223902, 0.20463978, 0.25902825,
       0.19631537, 0.19913299, 0.18804302, 0.19177619, 0.18061465,
       0.20057923, 0.21888013, 0.20162852, 0.20854918, 0.21475492,
       0.21280476, 0.23243266, 0.15742685, 0.14478336, 0.11936849,
       0.12178639, 0.09726094, 0.12626039, 0.0869497 , 0.10172738,
       0.08098239, 0.08254009, 0.07874422, 0.07785006, 0.07391165,
       0.07932316, 0.08656427, 0.07920979, 0.08083574, 0.08000071])

In [82]:
norm_trn_D =(trn_D - meanVec)/stdVec
min_D = norm_trn_D.min(axis = 0)
max_D = norm_trn_D.max(axis =0)
norm_trn_D = (norm_trn_D - min_D)/(max_D - min_D)

In [83]:
norm_trn_D

array([[0.57197692, 0.28318514, 0.41817079, ..., 0.28365968, 0.4192993 ,
        0.53490495],
       [0.47253871, 0.23586057, 0.23945011, ..., 0.28365968, 0.4192993 ,
        0.53490495],
       [0.38944731, 0.30745011, 0.24152622, ..., 0.28365968, 0.4192993 ,
        0.53490495],
       ...,
       [0.80010765, 0.80177159, 0.50752543, ..., 0.59348049, 0.50614355,
        0.61147908],
       [0.79336874, 0.74538113, 0.51804255, ..., 0.66459608, 0.51621415,
        0.63423407],
       [0.81991586, 0.79426064, 0.51864489, ..., 0.62081194, 0.5590162 ,
        0.65385147]])

In [ ]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(hidden_layer_sizes = (32,54,68), activation = 'logistic',
                   solver = 'adam', learning_rate_init = 0.005,
                   max_iter = 1000, random_state = 1)

clf.fit(X_train,Y_train)

## MFCC_N_500 train

In [93]:
tst_N = np.load(r"Test_MFCC_N_500.npy")

In [94]:
tst_N

array([[-2.92812416e+00, -2.83080248e+00, -2.07061720e+00, ...,
        -9.62184878e-02,  3.02972881e-02, -8.63230496e-02],
       [-3.77160143e+00, -3.34311708e+00, -2.37026431e+00, ...,
        -8.80875054e-03,  6.43080618e-02, -3.20964690e-02],
       [-5.54383350e+00, -4.11870402e+00, -3.16204704e+00, ...,
         6.36538713e-02,  3.47964475e-02,  1.44860347e-02],
       ...,
       [-3.27317960e+00, -8.36013875e+00, -1.52720007e+00, ...,
         4.96859394e-02,  4.80233962e-02,  3.05086807e-02],
       [-3.42225965e+00, -8.69518852e+00, -1.68342019e+00, ...,
         3.79117264e-02,  1.98224449e-02, -3.82263846e-03],
       [-4.52759032e+00, -9.56876796e+00, -3.05045120e+00, ...,
         2.45349716e-02, -2.67795767e-03, -9.26595959e-03]])

In [95]:
tst_N.shape

(500, 60)

In [96]:
tst_S = np.load(r"Test_MFCC_S_500.npy")

In [97]:
tst_S

array([[ 0.41917104, -0.35943021, -0.11670848, ..., -0.0143717 ,
         0.07497655,  0.09364944],
       [-3.42459154, -1.56327886,  1.03020566, ..., -0.14739546,
         0.11188615,  0.08739909],
       [-3.85668411, -2.71293831,  0.97610767, ..., -0.20035203,
         0.08611681,  0.09223631],
       ...,
       [-2.07232147, -6.72852477, -3.18697873, ..., -0.05108576,
        -0.0945261 , -0.03401962],
       [-1.18059565, -6.314564  , -2.73071825, ...,  0.01928117,
        -0.04576275, -0.01663111],
       [-2.11002453, -6.55735006, -3.97901679, ...,  0.04419295,
         0.01158073,  0.02502564]])

In [98]:
tst_S.shape

(500, 60)

In [99]:
tst_D = np.append(tst_N, tst_S, axis = 0)

In [100]:
tst_D

array([[-2.92812416, -2.83080248, -2.0706172 , ..., -0.09621849,
         0.03029729, -0.08632305],
       [-3.77160143, -3.34311708, -2.37026431, ..., -0.00880875,
         0.06430806, -0.03209647],
       [-5.5438335 , -4.11870402, -3.16204704, ...,  0.06365387,
         0.03479645,  0.01448603],
       ...,
       [-2.07232147, -6.72852477, -3.18697873, ..., -0.05108576,
        -0.0945261 , -0.03401962],
       [-1.18059565, -6.314564  , -2.73071825, ...,  0.01928117,
        -0.04576275, -0.01663111],
       [-2.11002453, -6.55735006, -3.97901679, ...,  0.04419295,
         0.01158073,  0.02502564]])

In [101]:
tst_D.shape

(1000, 60)

In [102]:
meanVec = np.mean(tst_D, axis =0)

In [103]:
meanVec

array([-3.89686400e+00, -4.47769000e+00, -9.40018383e-01, -2.89496075e+00,
       -1.74378020e-01, -8.93203053e-01, -1.66551703e+00, -9.23750062e-01,
       -5.59179414e-01,  2.82118686e-01, -1.34535121e+00,  7.94430123e-02,
        6.31994784e-02, -2.75314003e-01,  2.24285350e-01,  3.43418154e-01,
       -5.66983654e-01, -1.80821407e-01, -3.09457758e-01, -4.71950949e-02,
        1.95952108e-03,  3.67054971e-02,  1.22703184e-02,  3.89519484e-02,
        2.76566728e-02,  5.24973657e-03, -7.65091976e-03, -5.27978605e-03,
        8.14971601e-03, -3.10838443e-02,  5.14253493e-03, -1.57445402e-02,
        1.33612618e-03, -3.26215218e-03, -2.49304965e-03, -2.34438479e-03,
       -8.89793587e-04,  9.25639552e-03, -8.73876485e-04, -7.43560133e-03,
       -2.37842323e-04,  6.41135407e-03,  6.73523470e-04,  1.11874237e-02,
       -4.68953643e-04, -2.49938562e-03, -2.95629782e-03,  1.47272994e-03,
       -2.00434978e-03, -4.56988549e-03,  3.24708269e-04, -8.41599696e-04,
        3.99050044e-04, -

In [104]:
stdVec = np.std(tst_D, axis =0)

In [105]:
stdVec

array([2.59927538, 3.08225774, 1.87494898, 1.43296048, 1.6126554 ,
       1.69551667, 0.9838747 , 1.03927865, 0.82040416, 1.03986319,
       0.78648668, 0.8973469 , 0.90621006, 1.34834736, 1.02822844,
       0.87149067, 0.98326733, 1.03148566, 1.23361806, 1.01365587,
       0.56851536, 0.55887563, 0.38752849, 0.35234801, 0.34413612,
       0.29520146, 0.24413656, 0.26038894, 0.19616609, 0.2306196 ,
       0.19067067, 0.18575471, 0.18796042, 0.19663126, 0.19251742,
       0.21551324, 0.21174941, 0.2157484 , 0.22845947, 0.22577272,
       0.22464951, 0.21887252, 0.14981101, 0.13634948, 0.13432737,
       0.12157555, 0.10084259, 0.11206801, 0.08176268, 0.08871255,
       0.07776039, 0.07453695, 0.07823926, 0.08180393, 0.07764092,
       0.08477383, 0.07916492, 0.08795404, 0.08514184, 0.08633071])

In [106]:
norm_tst_D =(tst_D - meanVec)/stdVec
min_D = norm_tst_D.min(axis = 0)
max_D = norm_tst_D.max(axis =0)
norm_tst_D = (norm_tst_D - min_D)/(max_D - min_D)

In [107]:
norm_tst_D

array([[0.61326009, 0.59667434, 0.36641648, ..., 0.50329851, 0.62769186,
        0.36184554],
       [0.56026488, 0.56193006, 0.33388082, ..., 0.61702085, 0.66906752,
        0.42599515],
       [0.44891652, 0.50933112, 0.24790911, ..., 0.7112966 , 0.6331653 ,
        0.48110189],
       ...,
       [0.6670297 , 0.33233767, 0.24520203, ..., 0.56201736, 0.47583854,
        0.42372009],
       [0.72305634, 0.36041177, 0.29474275, ..., 0.65356656, 0.53516136,
        0.44429055],
       [0.66466084, 0.34394644, 0.15920259, ..., 0.68597744, 0.60492232,
        0.49357015]])